### ISSUE TITLE
Make full screen on orientation change to landscape

### ISSUE THREAD

**Issue by jahidshohel** [bradmartin/nativescript-videoplayer#28] opened 2016-08-13 06:51 UTC
Right now the video doesn't get full screen when device orientation changes from portrait to landscape. Is there any way to achieve that? Any example?

**Comment by bradmartin** [comment] 2016-08-13 14:11
I don't have a sample, I'll try to get you something next week.

**Comment by jahidshohel** [comment] 2016-08-13 18:36
👍

**Comment by bradmartin** [comment] 2016-08-19 02:55
I don't have much time right now to provide a great sample, but I do have a potential solution 😄 . Months ago I wrote about how you can enter 'Immersive Mode' on Android, it's easy and the code is here: https://bradmartin.net/2016/03/10/fullscreen-and-navigation-bar-color-in-a-nativescript-android-app/ . So what you can do is take those flags in the code and when you detect an orientation change, execute that to go full screen and vice versa. Here is a plugin to stylistically define your layouts for orientations which has a helper method to determine the device orientation as well here: https://github.com/NathanaelA/nativescript-orientation#applicationgetorientation 

Combining the two options above you should be able to figure out a very nice solution, if you have any trouble with that approach and share some code I'll gladly help you out. If I get some time, I might try to add a method to toggle 'immersive mode' for this plugin on Android to make it easier for other devs to consume.

Hope this helps 👍

**Comment by shnhwk** [comment] 2016-09-19 18:39
Anyone had any luck with this?

**Comment by bradmartin** [comment] 2016-09-19 19:04
I might have some time this week to add in a public method to make the video fullscreen, initially on Android. I'll need someone to cover the iOS specifics but I'll work on it soon, possibly today if things stay quiet 😄

**Comment by shnhwk** [comment] 2016-09-19 19:06
!!! Everyone leave Brad alone !!! 

I've been trying your Immersive Mode suggestion, but I'm having all kinds of issues with object references in the Orientation changed event.

**Comment by bradmartin** [comment] 2016-09-19 19:36
Haha I'll try to get something done. Haven't tried it but I'll let you know
what I run into

**Comment by shnhwk** [comment] 2016-09-20 01:49
I was finally able to get it working. Only issue now is I can't figure out how to clear these flags so all my pages aren't in immersive mode.

**Comment by bradmartin** [comment] 2016-09-20 02:23
Haha easily fixed. I added some stuff to the Swiss army knife that removes
the flags, so you can prob dig in that source for it

**Comment by bradmartin** [comment] 2016-09-28 14:28
Closing this as duplicate of https://github.com/bradmartin/nativescript-videoplayer/issues/14

**Closed by bradmartin** 2016-09-28 14:28 UTC
Labels: enhancement
