### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Milewski** [bradmartin/nativescript-videoplayer#10] opened 2016-03-19 06:26 UTC
doesnt matter what i do the screen is all white, i only can hear the video but cant see it.

**Comment by bradmartin** [comment] 2016-03-19 07:13
https://github.com/bradmartin/nativescript-videoplayer/issues/8

See if that works, I haven't had time to add the Z order to the plugin to fix this. I also need to confirm with the team what changed since 1.5 when it was working.

**Comment by bradmartin** [comment] 2016-03-21 14:33
Just updated the plugin on npm with the added code for Android to make it visible due to a layering issue with the views.

**Comment by MiroValchev** [comment] 2016-03-30 12:49
@bradmartin there is one caveat though, Z order puts the video on top of everything! For example, if you want to have subtitles showing over the video it won't work. Due to the Z order, the video will appear on top of the label with subs no matter what you do :(

**Comment by Ivshti** [comment] 2016-03-30 13:03
@bradmartin do you have an idea what the layering issue is exactly? is there another solution other than the ZOrderOnTop which would allow us to draw elements on top of the video?

**Comment by bradmartin** [comment] 2016-03-30 13:35
@MiroValchev @Ivshti - I don't know the exact issue. It was not an issue with NativeScript 1.5, the time I developed the plugin. I've asked the team what possibly changed with the layouts/page to cause the issue and they said it was present with 1.5, which it must be a device/android api issue if that's the case because I developed and tested it fine with NS 1.5.

As for using `setZOrderOnTop(true)` - we could make it an optional setting and use it in your XML like so: `android:zOrder="true/false"` but then if it's false I'm worried it won't render. I'll ping someone on the team to see if they have any suggestions on the best way to handle this to avoid issues later on.

**Comment by Ivshti** [comment] 2016-03-30 13:41
@bradmartin well I think it's related to the version.

We all kept testing with the same emulators/images/conditions, only thing that changed was {N} version.

Can you point us to whomever you asked and maybe tag them in this thread?

It doesn't render if we don't use `setZOrderOnTop`. Again, same issue didn't exist in 1.5, and we were able to draw subtitles/other elements on top of that

**Comment by enchev** [comment] 2016-03-30 13:47
Hey @Ivshti,

Actually I've suggested to @MiroValchev and @bradmartin to use this setting based on this thread:
http://stackoverflow.com/questions/19650483/video-is-not-showing-on-videoview-but-i-can-hear-its-sound

We've tested locally with simple Placeholder and VideoView in 1.5 and the issue was present. Here is an example:
```XML
<Page>
  <Placeholder creatingView="creatingView" />
</Page>
```

```JavaScript
exports.creatingView = function (args) {
   var v = new android.widget.VideoView(args.context);
   v.setVideoURI(android.net.Uri.parse("https://clips.vorwaertsgmbh.de/big_buck_bunny.mp4"));
   // v.setZOrderOnTop(true);
   v.requestFocus();
   v.start();
   args.view = v;
}
```

**Comment by bradmartin** [comment] 2016-03-30 20:47
### 1.5

![video1dot5](https://cloud.githubusercontent.com/assets/6006148/14156930/82287456-f68e-11e5-95f6-d8a2887736c6.gif)

### 1.6

![video1dot6](https://cloud.githubusercontent.com/assets/6006148/14156936/88a312fa-f68e-11e5-9a68-b7516a80b79f.gif)

I haven't went digging into the core modules to see if I can find anything yet, but something happened I'm certain now. Just need to find the cause. Hopefully nothing major and a better solution can be found than `setZOrderOnTop(true)` which prevents laying views on top of the player.

**Comment by enchev** [comment] 2016-03-31 06:46
Hmm that's weird. I've double checked once again the code I've posted in my previous reply and here is the result:
![untitled](https://cloud.githubusercontent.com/assets/5804953/14167574/e0b4f2e2-f724-11e5-8a9d-cda70024f8f2.png)

I've made:
```
npm uninstall -g nativescript
npm install -g nativescript@1.5.0
tns create TestApp
cd TestApp
npm uninstall tns-core-modules
npm install -g tns-core-modules@1.5.0
tns platform add android
tns run android
```

**Comment by enchev** [comment] 2016-03-31 07:23
Hey folks,

You are right! Please accept my excuses! 

I've finally replicated the problem and we will do our best to find immediately what's going on and how to fix it.

**Comment by enchev** [comment] 2016-03-31 07:58
You can monitor this issue:
https://github.com/NativeScript/NativeScript/issues/1874

**Comment by Ivshti** [comment] 2016-03-31 08:42
@bradmartin thanks for confirming it
@enchev great to see that we have a thread for the issue! Let us know on developments or/and if we can do anything to assist

**Comment by Ivshti** [comment] 2016-03-31 13:08
@enchev thanks for the idea, we'll try it and inform you very soon

**Comment by bathejasumeet** [comment] 2016-04-01 08:27
@bradmartin 
  I just stumbled into this thread since I am working on a custom video player with controls, and I had accomplished it , which worked till nativescript 1.5.2 but broke in 1.6/1.7 with this same issue of video being invisible. With respect to all that you said, it is true, setZOrderOnTop/setZOrderMediaOverlay seem to place the video view's surface view above the window, but this prevents overlaying custom controls on the video view(play/pause and seek bars), which perfectly worked till 1.5. I am aware of in and outs of video view, if you need any help fixing it, I am game ( it would be fun to have a video app on nativescript 1.7, since it is launches faster on android)

**Comment by Ivshti** [comment] 2016-04-01 08:32
@bathejasumeet we use a fork of nativescript-video for a production app, and we had the same case with 1.5 vs 1.6/1.7; we worked it around by reverting to 1.5, but after we complete our alpha release we will be also available to help for resolving the issue.

See this -> https://github.com/NativeScript/NativeScript/issues/1874 for the progress

**Comment by bathejasumeet** [comment] 2016-04-01 09:51
@bradmartin @Ivshti @bradmartin 
Guys, just ran a couple of tests  , these are my findings
adding the native android.widget.MediaController to the videoView in nativescript 1.7 does not seem to hide it, it overlays perfectly.

```
        nativeVideoView= new android.widget.VideoView(args.context);
        nativeVideoView.setZOrderMediaOverlay(true);
        nativeVideoView.setZOrderOnTop(true);
        var mediaController = new android.widget.MediaController(args.context);
        mediaController.setAnchorView(nativeVideoView);
        nativeVideoView.setMediaController(mediaController);
```

Can we reverse engineer?

**Comment by bathejasumeet** [comment] 2016-04-01 09:59
@enchev  
as per android docs :

> [ "The MediaController will create a default set of controls and put them in a window floating above your application. Specifically, the controls will float above the view specified with setAnchorView()" ](http://developer.android.com/reference/android/widget/MediaController.html)

, I think we should target for achieving this behavior in interim, I mean trying to make the view with controls float over the VideoView like MediaController does.

**Comment by bradmartin** [comment] 2016-04-01 14:32
@bathejasumeet - I meant to build this plugin with that as an option, to put the controls on top of the VideoView. I think I just forgot about it after my test run before making the actual android side of the plugin :) If you want to submit a PR with an optional attribute to set the controls on top of the VideoView that would be great. I'll create an issue with this as something needing to be done so it's not lost.

I also need to add a full screen option, again, just something I didn't have time to fully implement and NS needed a video plugin for devs less familiar with native controls so I wanted to ship it once it was decently functional.

**Comment by MiroValchev** [comment] 2016-07-05 12:19
@bradmartin I can confirm that this has been fixed in {N} 2.1. Still, you have to remove the hack:

this._android.setZOrderOnTop(true);

**Comment by bradmartin** [comment] 2016-07-05 12:49
Thanks for confirming. I'll update the package.

**Comment by bradmartin** [comment] 2016-07-05 20:33
Just published the update.

**Closed by bradmartin** 2016-07-05 20:33 UTC
