### ISSUE TITLE
Videoplayer resizes in a weird way on screen orientation change

### ISSUE THREAD

**Issue by JoepDriesen** [bradmartin/nativescript-videoplayer#64] opened 2017-04-03 16:26 UTC
Hi,

not sure if I'm doing something wrong, but the videoplayer is misbehaving on screen orientations.

videoplayer.xml:
`<Page loaded="loaded" unloaded="page_unloaded" actionBarHidden="true" xmlns:VideoPlayer="nativescript-videoplayer">

    <StackLayout id="player-container" backgroundColor="black">

        <VideoPlayer:Video id="player" controls="false" loop="false" autoplay="true" src="~/videos/test.mp4" />

    </StackLayout>
</Page>`

This displays the video nicely centered vertically, but when the screen orientation changes, it seems to keep the same padding above the videoplayer, which makes the videoplayer height smaller instead of using the entire screen height. 
This also makes the aspect ratio very warped.

![illustration](https://cloud.githubusercontent.com/assets/12200799/24619626/e928a1b0-189a-11e7-932b-6ad0df18dc90.png)

And ideas what is going wrong?

**Comment by bradmartin** [comment] 2017-04-03 16:50
Does player-container have styles by the id?  Just needs some layout
tweaking I think. You could prob apply different styles using the
orientation plugin to change when needed to scale the players height/width
or position in the layout.

**Comment by bnussey** [comment] 2017-04-03 17:54
Is this on Android or iOS? Or both?

**Comment by JoepDriesen** [comment] 2017-04-03 18:48
it's on android, haven't tested iOS.

I have tried applying multiple styles on the wrapper and changing the styles when the orientation changes, but not of it really changed anything. The biggest issue seems to be that the videoplayer element doesn't adjust it's height when it is set dynamically in javascript...

**Comment by bnussey** [comment] 2017-04-03 18:50
Try adjusting this:

fill - (boolean) - optional ANDROID ONLY
If set to true, the aspect ratio of the video will not be honored and it will fill the entire space available.

**Comment by JoepDriesen** [comment] 2017-04-03 19:03
@bnussey 
Thanks! This does fix the padding problem, but in portrait mode it stretches the video as well. Is there a way to figure out the aspect ratio of an mp4 file so I can set it manually?

**Comment by bnussey** [comment] 2017-04-03 19:06
Hey @JoepDriesen great to hear.. Im sure there is a way just don't know it off the top of my head. However you could use this to set it programmatically - https://github.com/NathanaelA/nativescript-orientation

Closing the issue for now.

**Closed by bnussey** 2017-04-03 19:06 UTC

**Comment by Niko87** [comment] 2017-05-11 17:42
do you have resolved this??? the only way i could, is to set fill="true" (but in portrait isn’t good)..... the nativescript-orientation don’t resolve anything... i don’t know why you close this issue within any good answer...

**Comment by bnussey** [comment] 2017-05-11 18:04
If you can replicate this on the demo, I will re-open it.

**Comment by Niko87** [comment] 2017-05-15 08:26
the problem is when the video is bigger than the demo video, if you set the height and fill="false", when landscaping, the video doesn't maintain the aspect ratio. If height not defined, the video display as  JoepDriesen says... 

in my case is a ng2 app, this is the xml
<GridLayout columns="*" rows="*">

  <VideoPlayer fill="false" col="0" row="0" src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" autoplay="true" controls="true"></VideoPlayer>

</GridLayout>

paste it in your demo... and you may see the issue...

Thanks..

**Comment by jibon57** [comment] 2017-05-19 14:19
Hi,
I am facing same problem as @Niko87 :( changing orientation player doesn't adjusting it's aspect ratio.

**Comment by Niko87** [comment] 2017-05-22 19:08
if you like to replicate in the demo, without change anything, just start the demo landscape , an then turn into portrait... the aspect ratio will be lost..  

Tanks for the support!

**Comment by lucasromanojf** [comment] 2019-02-07 16:48
I have the same issue.

**Comment by jjstrat3** [comment] 2019-05-24 02:35
I also have this issue, but only on Android.  It's very annoying to say the least.  My use case is using a gridlayout with the video player set inside with a row=0 so that I can custom controls overlaid above and below.
